### ISSUE TITLE
The game freezes when I'm opening cheat menu at game's main menu

### ISSUE THREAD

**Issue by justaguy31** [Frouk3/mgrCheat#1]
It's simple, I press cheat menu keybind (NumPad0) - the game goes softlocked as if timestop was turned on there.
2D effects of main menu work, but it just doesn't reply to my actions. Raiden doesn't move aswell there.
I haven't tested other menus though, but i think the result will be the same.

**Comment by justaguy31** [comment]
Trying to open the menu too early when booting up the game causes black screen obviously.

**Comment by Frouk3** [comment]
open menu when you are in game menu, i didn't found any problems in my instance and in another people instance that you currently have, maybe try to switch "Pause when menu is shown"

**Comment by justaguy31** [comment]
well i did exactly this, and no this is not "Pause when menu is shown", that looks like a useful thing
the game really just softlocks when i open up cheat menu and close it in game main menu

**Comment by justaguy31** [comment]
so i guess the game pause is not intended by you

**Comment by Frouk3** [comment]
can you send SHA1 checksum of your .exe?

**Comment by justaguy31** [comment]
ad6750825e2158a9e5cbaf31f90d23c9e4948746

**Comment by Frouk3** [comment]
that's strange, where did you download menu?

**Comment by justaguy31** [comment]
right from github release, and my theory about timestop was right. i just quitted a level with it enabled and the game got softlocked again. but why does that happen when i open the cheat menu?

**Comment by Frouk3** [comment]
> right from github release, and my theory about timestop was right. i just quitted a level with it enabled and the game got softlocked again. but why does that happen when i open the cheat menu?

try to download menu from nexus https://www.nexusmods.com/metalgearrisingrevengeance/mods/93

**Comment by justaguy31** [comment]
now i see, the github release seems to be outdated. thank you
